apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: microshop
type: Opaque
stringData:                          # stringData 可以直接写明文，K8s 会自动 base64 编码
  MYSQL_ROOT_PASSWORD: "MicroShop@123"   # 学习环境写明文，生产环境用密钥管理系统
